# Generated by Django 4.2.13 on 2024-06-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_name', models.CharField(max_length=100)),
                ('num_attending', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('time_slot', models.CharField(choices=[('10:00', '10:00 AM - 12:00 PM'), ('14:00', '2:00 PM - 4:00 PM')], max_length=5)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('date', 'time_slot')},
            },
        ),
    ]
